{% set data = load_setup_py_data() %}

package:
  name: c2dataviewer
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: 0
  entry_points:
    - c2dv = c2dataviewer.c2dv:main

test:
  source_files:
    - test

requirements:
  build:
    - python {{ python }}
  run:
    - pyqt
    - psutil
    - pvapy
    # 0.13 removes support for PlotItem::rotate used in image_profile_display.py.
    # Hardcode version until we find an alternative.
    # Note that this is also hardcoded in requirements.txt
    - pyqtgraph=0.12.4
    - python-blosc
about:
  home: https://git.aps.anl.gov/C2/conda/data-viewer
  license: APS
  summary: APS C2 data viewer

