package:
  name: C2DataViewer
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}
  entry_points:
    - c2dv = C2DataViewer.c2dataviewer:main

requirements:
  build:
    - python {{ python }}
  run:
    - numpy
    - opencv
    - psutil
    - pvapy
    - pyqtgraph
    - python
