{% set data = load_setup_py_data() %}

package:
  name: c2dataviewer
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  entry_points:
    - c2dv = c2dataviewer.c2dv:main

test:
  source_files:
    - test
  
requirements:
  build:
    - python {{ python }}
  run:
    - numpy
    - psutil
    - pvapy
    - epics-base  # [osx]
    - pyqtgraph
    - python
