{% set data = load_setup_py_data() %}

package:
  name: c2dataviewer
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: 0
  entry_points:
    - c2dv = c2dataviewer.c2dv:main

test:
  requires:
    - pyqt
  source_files:
    - test

requirements:
  build:
    - python {{ python }}
  run:
    - psutil
    - pvapy
    # We are using fixed version until https://git.aps.anl.gov/C2/conda/data-viewer/-/issues/48
    # is resolved. Note that this is also hardcoded in tox.ini and setup_pip.py.
    - pyqtgraph=0.12.4
    - python-blosc
    
about:
  home: https://git.aps.anl.gov/C2/conda/data-viewer
  license: APS
  summary: APS C2 data viewer

